#' Check meteo data input as required by the 3DCMCCFEM model
#'
#' \code{check_meteo_3DFEM} perform some basic test on the variables in the
#' input meteo file (e.g., generated by the function \code{make_meteo_EOBS}) to
#' ensure compatibility with \code{run_3DFEM}. The function can also try to
#' correct inconsistency
#'
#' @param file_meteo Character or data.frame: path to meteo.txt file or
#'   data.frame of meteo.txt file read with read.table.
#' @param make_report Logical: make a report of the input meteo file? To be
#'   implemented yet.
#' @param correct Logical: correct any errors found? Default to TRUE.
#' @param save Logical: save meteo file?. Only if file_meteo is a path to a
#'   file. If TRUE, meteo file is saved with the same name and same directory of
#'   file_meteo. Default to FALSE
#' @param plot Logical: plot meteo file with \code{plot_meteo_3DFEM}?. Default
#'   to FALSE.
#' @param ... additional argument passed to \code{plot_meteo_3DFEM} when
#'   \code{plot=TRUE}
#'
#' @details The function check for consistency with the columns name convention
#'   of the model, for NA, missing data, missing observation in the weather time
#'   series, anomalous values in precipitation and temperature relations (i.e.,
#'   Tmin<=Tmean<=Tmax). If \code{correct=TRUE} colnames and temperature are
#'   fixed according to model specifications. After all checks, if
#'   \code{plot=TRUE} the function \code{plot_meteo_3DFEM} is call.
#'
#' @return a data.frame with the corrected weather time series if
#'   \code{correct=TRUE}, invisible otherwise. If \code{plot=TRUE} the function
#'   return a ggplot object if \code{save_plot=FALSE}. If \code{save_plot=TRUE}
#'   the function save in \code{outdir} a png file with the name of the site in
#'   \code{meteo_path_file}
#'
#' @seealso \code{\link[=run_3DFEM]{make_meteo_EOBS}} and
#'   \code{\link[=run_3DFEM]{plot_meteo_3DFEM}}
#' @export
#'


check_meteo_3DFEM <- function(file_meteo,make_report=FALSE,correct=TRUE,save=FALSE,plot=FALSE,...){

# input check -------------------------------------------------------------



  stopifnot("make_report must be logical"=check_log(make_report),
            "correct must be logical"=check_log(correct),
            "plot must be logical"=check_log(plot))

# read data -----------------------------------------------------------------

  if(class(file_meteo)=="character"){
  meteo <- data.table::fread(file_meteo)
 }else if (class(file_meteo)%in%c("data.frame","data.table","tbl_df","tbl" )){
   meteo <- file_meteo
 }else stop("file_meteo is of the wrong class")

# check colnames ----------------------------------------------------------
 col_df <- data.frame(ref_col=c("Year","Month","n_days","Rg_f","Ta_f","Tmax","Tmin","RH_f","Ts_f","Precip","SWC", "LAI","ET","WS_f"),
                      col = colnames(meteo))
 if(!identical(col_df$col, col_df$ref_col)){
   wrong_col <-col_df[col_df$ref_col!=col_df$col,]
   warning("There are some column(s) with wrong name. Check the names convention for the model.\n",paste0(wrong_col,sep=" "))
   if(correct){
     colnames(meteo) <- col_df$ref_col
   }else {stop()}
   }
# check for missing data --------------------------------------------------

 check_year <- function(seq) {
   ref_seq <- min(seq,na.rm=T):max(seq,na.rm=T)
   missing <- ref_seq[!ref_seq %in% seq]
   return(if (length(missing) != 0)
     warning(
       "there are missing year(s) in the sequence. Missing year(s) are\n",
       paste0(missing, sep = "\n")
     ))
 }

 check_year(meteo$Year)

 year_day <- as.data.frame(table(meteo$Year),stringsAsFactors = FALSE)
 year_day$Var1 <- as.numeric(year_day$Var1)
 year_day$leap <- lubridate::leap_year(year_day$Var1)
 year_day$ref <- ifelse(year_day$leap==F,365,366)
 test_year <- year_day$Freq-year_day$ref

 if(any(test_year!=0)){
  check <- test_year!=0
  warning("Year(s) ",paste0(year_day$Var1[check],sep=" "), "have wrong numbers of day: ",paste0(year_day$Freq[check],collapse=" "),". Should be: ",paste0(year_day$ref[check],collapse=" "))
 }

 month_day <- meteo %>% dplyr::group_by(Year) %>% dplyr::summarise(nmonth=length(unique(Month)))
 month_day$ref <- 12
 test_month <- year_day$Freq-year_day$ref

 if(any(test_month!=0)){
   check <- test_month!=0
   warning("Year(s) ",paste0(month_day$Year[check],sep=" "), "have wrong numbers of months: ",paste0(month_day$nmonth[check],collapse=" "),". Should be: ",paste0(month_day$ref[check],collapse=" "))
 }

if(sum(!complete.cases(meteo))!=0)warning("row(s) ",paste0(which(!complete.cases(meteo)),collapse=" ")," contain some missing data. Please check")

# check data -------------------------------------------------------------

 if(all(meteo$Rg_f<=0))warning("Solar radiation is negative for row(s): \n",paste0(which(meteo$Rg_f<=0),sep="\n"))
 if(all(meteo$RH_f<=0))warning("Relative humidity is negative for row(s): \n",paste0(which(meteo$RH_f<=0),sep="\n"))
 if(all(meteo$RH_f>100))warning("Relative humidity is greater than 100 for row(s): \n",paste0(which(meteo$RH_f>100),sep="\n"))
 if(all(meteo$Rg_f>60))warning("Solar radiation is greater than 60 for row(s): \n",paste0(which(meteo$Rg_f>60),sep="\n"))
 if(all(meteo$Precip<=0))warning("Precipitation is negative for row(s): \n",paste0(which(meteo$Precip<=0),sep="\n"))


# check temperature relations ----------------------------------------------

 ind1 <- meteo$Tmin<meteo$Ta_f
 ind2 <-  meteo$Ta_f<meteo$Tmax
 ind <- ind1&ind2


 if(any(!ind)){

   warning("There are ",sum(!ind)," row(s) in which temperatures are wrong!")

   if(correct){
     meteo[!ind1,"Tmin"] <-  meteo[!ind1,"Ta_f"]
     meteo[!ind2,"Tmax"] <-  meteo[!ind2,"Ta_f"]
     }
 }

 pr <- meteo$Precip<0.05&meteo$Precip!=0

 if(any(pr)){

   warning("There are ",sum(pr)," row(s) in which precipitation is less than the precision of the model!")

   if(correct){
     meteo[pr,"Precip"] <-  0
   }
 }

 if(save&class(file_meteo)=="character"){
   write.table(meteo,file_meteo,row.names=F,col.names=T,quote=FALSE,sep="\t")
   message(file_meteo, " saved!")
   if (plot) {
     R3DFEM::plot_meteo_3DFEM(file_meteo,
                              daterange = c(paste0(meteo[1, 1:3], collapse ="-"),
                                            paste0(meteo[nrow(meteo), 1:3], collapse = "-")),...)
   }
 }

 if(correct)return(invisible(meteo))
 return(invisible())
}

