#' Create the stand input file for 3DCMCCFEM model
#'
#' \code{make_stand_INFC} use Italian INFC 2005 and 2015 data to produce the
#' stand.txt file needed by the function 3DFEM. The function can use both
#' stand-level and tree-level data. More information about INFC data can be
#' found  \href{https://www.inventarioforestale.org/it/}{here}
#'
#' @param id Numeric vector: IDs of INFC plot.
#' @param mode Character: one of "tree-level", "stand-level". From which
#'   database should the data be taken?
#' @param year Character: one of "2005","2015","both". From which year should
#'   the information be taken?
#' @param make_topo Logical: If TRUE use the function \code{make_topo} to create
#'   also the topo file according to the INFC database
#' @param site Character: Name of the site. Used to construct output name
#' @param outdir Character: path to the output directory.
#'
#' @details The function can accept a vector of IDs and return as many files as
#'   the length of the ID vector.The output stand file has the following columns:
#'   \itemize{
#'   \item \emph{Year}: Reference year for the data
#'   \item \emph{x}: x cell position
#'   \item \emph{y}: y cell position
#'   \item \emph{Age}: Age of the stand
#'   \item \emph{Species}: Species present within the stand
#'   \item \emph{Managment}: Is the stand managed: Logical
#'   \item \emph{N}: Numbers of trees per hectare
#'   \item \emph{Stools}: Number of stool per cell*
#'   \item \emph{AvDBH}: Average Diameter at Breast Height for the species (in
#'   cm)
#'   \item \emph{Height}: Avarage height of the species (in m)
#'   \item \emph{Wf}:Foliage biomass*
#'   \item \emph{Wrc}: Coarse root biomass *
#'   \item \emph{Wrf}: Fine root biomass*
#'   \item \emph{Ws}: Steam biomass*
#'   \item \emph{Wbb}: Branch and bark biomass*
#'   \item \emph{Wres}: Reserve biomass*
#'   \item \emph{Lai}: Leaf Area Index of the stand*
#'   }
#'   All the data in the input file are referred to the dimension of the INFC
#'   plot (i.e., 530 m2). Inputs signed with * are not mandatory for the model.
#'   The stand file generated by the function will have a row for each year (if
#'   year="both") and each species found in the plot (when mode="tree-level) or a
#'   single row with average plot data (when mode="stand-level"). The age is
#'   always retrieve from the stand-level database. For more info on the stand
#'   input data needed to see the official \href{
#'   http://eprints.bice.rm.cnr.it/22393/1/3D-CMCC-FEM_User_Guide_v.2_July_2023.pdf}{User's
#'   Guide}
#'
#' @return Used for its side effects.It save in \code{outdir} as many stand
#'   input files as the length of the IDs provided
#' @seealso \code{\link[=run_3DFEM]{run_3DFEM}}
#' @export


make_stand_INFC <-
  function(id,
           mode = c("tree-level", "stand-level"),
           year=c("2005","2015","both"),
           make_topo=FALSE,
           site = NULL,
           outdir = NULL) {

    # load data ---------------------------------------------------------------

    #deco cat
    specie <- R3DFEM::specie
    tl_specie <- R3DFEM::tree_level_species
    #shp
    nfi05 <- R3DFEM:::shp_infc05
    nfi15 <- R3DFEM:::shp_infc15
    #IDs
    id05 <- nfi05$idpunto
    id15 <- nfi15$idpunto

    # IDs check ---------------------------------------------------------------

    if (!all(id %in% id05)) {
      message("ID ",
              paste0(id[!id %in% id05], collapse = " "),
              " not present in the INFC 2005 database")

    }
    if (!all(id %in% id15)) {
      message("ID ",
              paste0(id[!id %in% id15], collapse = " "),
              " not present in the INFC 2015 database")

    }

    id <- id[id %in% id05]
    id <- id[id %in% id15]
    if(length(id)==0)stop("there is no id left after check")


    # other args check --------------------------------------------------------

    check_dir(outdir)

    if (is.null(site)) {
      warning("Argument 'site' is missing with no default. A temporary name will be given.")
      site <- "tmp"
    }

    possible.arg <-
      c("tree-level", "stand-level")
    match.arg(mode, possible.arg)

    possible.year <-
      c("2005","2015","both")
    match.arg(year, possible.year)

    if (mode == "tree-level") {
      #tree level
      tl_nfi05 <- R3DFEM:::tl_infc05
      tl_nfi15 <- R3DFEM:::tl_infc15
    }

    # from stand-level -----------------------------------------------------------


    coord <- nfi05[nfi05$idpunto %in% id, "geometry"]
    t05 <-
      nfi05[nfi05$idpunto %in% id, c("idpunto", "eta_media_", "codcfor", "napv_ha", "dbh", "h")]
    t15 <-
      nfi15[nfi15$idpunto %in% id, c("idpunto", "eta_media_", "codcfor", "napv_ha", "dbh", "h")]
    t15$codcfor <- as.numeric(t15$codcfor)
    eta <-
      c(
        "1" = 10,
        "2" = 20,
        "3" = 30,
        "4" = 40,
        "5" = 60,
        "6" = 100,
        "7" = 125,
        "8" = NA
      )
    col_name <-
      c(
        "id",
        "Year",
        "x",
        "y",
        "Age",
        "Species",
        "Management",
        "N",
        "Stool",
        "AvDBH",
        "Height",
        "Wf",
        "Wrc",
        "Wrf",
        "Ws",
        "Wbb",
        "Wres",
        "Lai"
      )
    if (mode == "stand-level") {
      stand05 <-
        data.frame(
          id = t05$idpunto,
          2005,
          0,
          0,
          eta[as.character(t05$eta_media_)],
          specie[specie$cod %in% t05$codcfor, 2],
          "T",
          t05$napv_ha,
          0,
          t05$dbh,
          t05$h,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        )
      stand15 <-
        data.frame(
          id = t15$idpunto,
          2015,
          0,
          0,
          eta[as.character(t05$eta_media_)] + 10,
          specie[specie$cod %in% t15$codcfor, 2],
          "T",
          t15$napv_ha,
          0,
          t15$dbh,
          t15$h,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        )

      colnames(stand05) <- col_name
      colnames(stand15) <- col_name

      if (length(id) != 1) {
        for (i in 1:length(id)) {
          out <-
            rbind(stand05[stand05$id == id[i], ], stand15[stand15$id == id[i], ])
          out$id <- NULL

          if(year=="2005"){
            out <- out[out$Year==2005,]
          }else if(year=="2015"){
            out <- out[out$Year==2015,]
          }else{
            out <- out
          }

          write.table(
            out,
            paste0(outdir, "/", site, "_", id[i], "_sl_stand.txt"),
            row.names = F,
            col.names = T,
            quote = FALSE,
            sep = ","
          )
          message(
            "file ",
            paste0(outdir, "/", site, "_", id[i], "_sl_stand.txt"),
            " saved in stand-level mode for ",year," year"
          )
        }
      } else{
        stand <- rbind(stand05, stand15)
        stand$id <- NULL

        if(year=="2005"){
          out <- stand[stand$Year==2005,]
        }else if(year=="2015"){
          out <- stand[stand$Year==2015,]
        }else{
          out <- stand
        }

        write.table(
          out,
          paste0(outdir, "/", site, "_sl_stand.txt"),
          row.names = F,
          col.names = T,
          quote = FALSE,
          sep = ","
        )
        message("file ",
                paste0(outdir, "/", site, "_sl_stand.txt"),
                " saved in stand-level mode for ",year," year")
      }

      # from tree-level ---------------------------------------------------------

    } else{

      for (i in seq_along(id)) {
        single_plot_data <- tl_infc05[tl_infc05$idpunto == id[i], ]
        spcod <- unique(single_plot_data$SPcod)

        tl05 <- lapply(spcod, function(x) {
          sp_data <- single_plot_data[single_plot_data$SPcod == x, ]
          treelevel05 <-
            data.frame(
              id <- id[i],
              2005,
              0,
              0,
              unname(eta[as.character(t05$eta_media_)])[i],
              tl_specie[tl_specie$fdcod == x, "FOREST.CLASS"],
              "T",
              sum(sp_data$FEha),
              0,
              mean(sp_data$Dapv),
              mean(sp_data$Hapv),
              0,
              0,
              0,
              0,
              0,
              0,
              0
            )
          colnames(treelevel05) <- col_name
          return(treelevel05)
        })

        tl05 <- do.call(rbind, tl05)
        tl05$id <- NULL

        single_plot_data15 <- tl_infc15[tl_infc15$idpunto == id[i], ]
        spcod15 <- unique(single_plot_data15$SPcod)

        tl15 <- lapply(spcod15, function(x) {
          sp_data <- single_plot_data15[single_plot_data15$SPcod == x, ]
          treelevel15 <-
            data.frame(
              id <- id[i],
              2015,
              0,
              0,
              unique(tl05$Age)+10,
              tl_specie[tl_specie$fdcod == x, "FOREST.CLASS"],
              "T",
              sum(sp_data$FEha),
              0,
              mean(sp_data$Dapv),
              mean(sp_data$Hapv),
              0,
              0,
              0,
              0,
              0,
              0,
              0
            )
          colnames(treelevel15) <- col_name
          return(treelevel15)
        })

        tl15 <- do.call(rbind, tl15)
        tl15$id <- NULL

        df <- as.data.frame(rbind(tl05,tl15))

        if(year=="2005"){
          out <- tl05
        }else if(year=="2015"){
          out <- tl15
        }else{
          out <- df
        }

        write.table(
          out,
          paste0(outdir, "/", site, "_", id[i], "_tl_stand.txt"),
          row.names = F,
          col.names = T,
          quote = FALSE,
          sep = ","
        )
        message(
          "file ",
          paste0(outdir, "/", site, "_", id[i], "_tl_stand.txt"),
          " saved in tree-level mode for ",year," year"
        )
      }
    }
    if(make_topo){
      for (i in seq_along(id)) {
        elev <- nfi05$dtm[nfi05$idpunto%in%id[i]]
        name_topo <-paste(site,id[i],sep="_")
        R3DFEM::make_topo(site=name_topo,elev = elev,outdir = outdir)

      }
    }
  }
