#' Plot the annual output of the 3DCMCCFEM model
#'
#' \code{plot_output_3DFEM} plot the variables in the output file of the model
#' (e.g., generated by the function \code{run_3DFEM}).
#'
#' @param output_3DFEM Character: path to the model output file.
#' @param x Character vector of length 1: variable name to be plotted in the
#'   x-axis. If not provided will be set to the variable "YEAR"
#' @param y Character vector: variable name to be plotted in the y-axis. Could
#'   be of length >1 if x is NULL. In this case variables will be plotted on
#'   different facets
#' @param site_name character vector of length 1: site name to be plotted as
#'   title. Optional
#' @param year_range numeric vector of length 2: starting and ending year from
#'   which to plot the data. It will be sorted in ascending order
#' @param window Numeric: dimension of the focal window for compute the rolling
#'   mean. Expressed in years Default to NULL (rolling mean is not plotted).
#' @param save_plot Logical: Should plots be saved in outdir? Default to FALSE.
#' @param outdir Character: path to the output directory.
#'
#' @details The function plots the time series of the variables specified by y.
#'   The \code{window} argument should be appropriate to the desired time frame.
#'   If x is provided, a scatterplot of the x vs y variable will be plotted and
#'   the window argument will be ignored.
#'
#' @return A ggplot object if \code{save_plot=FALSE}, invisible otherwise. If
#'   \code{save_plot=TRUE} the function save in \code{outdir} a png file. The
#'   file name will be constructed based on the argument provided (x,
#'   y, site_name, year_range, and window)
#'
#' @seealso \code{\link[=run_3DFEM]{run_3DFEM}}
#' @export
#'

  plot_output_3DFEM <-
  function(output_3DFEM,
           x=NULL,
           y=NULL,
           site_name=NULL,
           year_range=NULL,
           window = NULL,
           text_size = 40,
           save_plot=FALSE,
           outdir = NULL) {


# arg checks --------------------------------------------------------------
    stopifnot("output_3DFEM must be a length 1 character vector"=check_char(output_3DFEM),
              "var must be a character vector containing column names of the 3DFEM output"=!is.null(var)&&is.character(var))
    #read data
    df <- data.table::fread(output_3DFEM,sep=",",header=T,fill=T)
    df <- df[complete.cases(df),]
    possible.args <- colnames(df)

    if(is.null(x)&is.null(y))stop("If x is NULL y must be provided and must be a character vector of output variable of the model")
    if(is.null(y)&!is.null(x))stop("If x is provided, y must be provided and must be a character vector of output variable of the model")
    if(!is.null(y)&is.null(x)){
      y <- match.arg(y,possible.args,several.ok = T)
      x.axis <- "YEAR"
      cols <-c(x.axis,y)
      df <- df[,..cols]
      df <- data.table::melt(df,id.vars="YEAR")
    }
    if(!is.null(y)&!is.null(x)){
      stopifnot("If both x and y are defined, y must be character vector of length 1"=check_char(y),
                "If both x and y are defined, x must be character vector of length 1"=check_char(x))
      y <- match.arg(y,possible.args,several.ok = F)
      x <- match.arg(x,possible.args,several.ok = F)
      cols <- unique(c("YEAR",x,y))
      df <- df[,..cols]
    }

    if(!is.null(year_range)){
      stopifnot("If not NULL, year_range must be a numeric vector of length 2 "=check_len_num(year_range,2))
      year_range <- sort(year_range)
      df <- df[df$YEAR>=year_range[1]&df$YEAR<=year_range[2],]
    }

    # plot --------------------------------------------------------------------

    site_plot <- ggplot2::ggplot(df)+
      ggplot2::theme_classic(base_family = "sans")+
      ggplot2::theme(title = ggplot2::element_text(size = text_size-2),
            axis.title = ggplot2::element_text(size = text_size-6),
            axis.text = ggplot2::element_text(size = text_size-12),
            axis.text.x = ggplot2::element_text(angle=90),
            panel.spacing = ggplot2::unit(2, "lines"),
            legend.title = ggplot2::element_text(size = text_size-12),
            legend.text = ggplot2::element_text(size = text_size-18),
            legend.position = "none",
            legend.key.size = ggplot2::unit(2,"line"),
            legend.key.height=ggplot2::unit(1,"line"),
            legend.key = ggplot2::element_rect(linewidth=1,fill="transparent",color="transparent",linetype=0),
            strip.text = ggplot2::element_text(size = text_size-5),
            panel.grid.major = ggplot2::element_blank(),
            panel.grid.minor = ggplot2::element_blank(),
            strip.background = ggplot2::element_blank(),
            panel.background = ggplot2::element_rect(fill = 'transparent'),
            panel.border = ggplot2::element_rect(linetype = 'solid', fill = 'transparent', color='black',linewidth=1.2))



    if(!is.null(y)&is.null(x)){
      site_plot <- site_plot+ggplot2::geom_point(aes(x=YEAR,y=value,col=variable),size=2)

      if(length(y)==1){
      site_plot <- site_plot+ggplot2::labs(y=y)
      }else{
        site_plot <- site_plot+ggplot2::facet_wrap(~variable)
      }
      if(!is.null(window)){
        stopifnot("if not NULL window must be a numeric vector of length 1"=check_num(window))
        site_plot <- site_plot+
          ggplot2::geom_line(aes(col=variable,x=YEAR,y=ave(.data[["value"]], variable, FUN = function(Z) zoo::rollmean(Z, window, fill=NA, align='center'))),size=1.0)
      }
    }else{
      site_plot <-site_plot+ggplot2::geom_point(aes(x=.data[[x]],y=.data[[y]]),size=2)
    }

    if(!is.null(site_name)){
      stopifnot("site_name must be a character vector of legth 1"=check_char(site_name))
      site_plot <-site_plot+ggplot2::labs(title=site_name)
    }

    if(save_plot){

      check_dir(outdir)
      #salva il plot nell'outdir
      if(!is.null(site_name)){
        newname <- paste0(outdir,site_name,"_")
      }else{
        newname <- outdir
      }
      if(!is.null(y)&!is.null(x)){
        newname <- paste0(newname,x,"_vs_",y)
      }else {
        newname <- paste0(newname,paste0(y,collapse = "_"))
        if(!is.null(window)){
          newname <- paste0(newname,"_window_",window)
        }
      }

      if(!is.null(year_range)){
        newname <-paste0(newname,"_",paste0(year_range,collapse = "-"))
      }

      newname <- paste0(newname,".png")
      ggplot2::ggsave(newname,
             plot = site_plot, scale=2,width = 26,height = 13, units = "cm",
             dpi = 300)
      return(invisible(site_plot))
    }else{site_plot}
  }


#plot_output_3DFEM(output_3DFEM,x="RA",y=c("NPP"),save_plot = T,outdir = outdir,year_range = c(2006,2050),site_name = "a")

