#' Plot soil data input as required by the 3DCMCCFEM model
#'
#' \code{plot_soil_3DFEM} plot the textural information of a soil.txt file (e.g.,
#' generated by the function \code{make_soil_ISRIC}) required by the model.
#' Textural information is represented as the textural triangle with the USDA
#' system.
#'
#' @param soil_file_path Character vector: vector of paths to soil.txt input files.
#' @param save_plot Logical: Should plots be saved in outdir? Deafult to FALSE.
#' @param outdir Character: path to the output directory.
#' @inheritParams plotrix::triax.plot
#'
#' @details The function plots the textural characteristics of soil from the
#'   input soil.txt file required by the 3D-CMCC-FEM model. Based on the
#'   \code{plotrix} package. See plotrix::triax.plot for all possible arguments.
#'
#' @return Invisible. The function is called for its side effects. If
#'   \code{save_plot=TRUE} the function save in \code{outdir} a png file with
#'   the name of the site in \code{soil_file_path}
#'
#' @seealso \code{\link[=plot_meteo_3DFEM]{plot_meteo_3DFEM}}
#' @export
#'

plot_soil_3DFEM <-
  function (soil_file_path = NULL,
            save_plot=TRUE,
            outdir=NULL,
            main = "",
            show.names = TRUE,
            show.lines = TRUE,
            col.names = "gray",
            bg.names = par("bg"),
            show.grid = FALSE,
            col.axis = "black",
            col.lines = "gray",
            col.grid = "gray",
            lty.grid = 3,
            show.legend = FALSE,
            label.points = FALSE,
            point.labels = NULL,
            col.symbols = "red",
            pch = par("pch"),
            ...){

    # argument check ----------------------------------------------------------


    if(length(soil_file_path)!=1){

      sl <- lapply(soil_file_path,read.table,header = T, sep = ",")
      sl <- do.call(rbind,sl)

    }else{

      if(!check_char(soil_file_path))stop("soil_file_path should be a valid path to a soil.txt file")
      sl <- read.table(soil_file_path, header = T, sep = ",")

    }

    texture <- sl[, 8:6]

    # base param --------------------------------------------------------------
    axis.labels = c("percent sand", "percent silt", "percent clay")

    tick.labels = list(
      l = seq(10, 90, by = 10),
      r = seq(10, 90, by = 10),
      b = seq(10, 90, by = 10)
    )
    at = seq(0.1, 0.9,
             by = 0.1)


    if(save_plot){
      check_dir(outdir)
      name <- basename(soil_file_path)
      site <- gsub("_soil.txt","",name)
      filename <- file.path(outdir,paste0(site,".png"))
      png(filename,width = 40,height = 30, units = "cm",res=300)
      }


    # main function -----------------------------------------------------------

    plotrix::triax.plot(
      x = NULL,
      main = main,
      at = at,
      axis.labels = axis.labels,
      tick.labels = tick.labels,
      col.axis = col.axis,
      show.grid = show.grid,
      col.grid = col.grid,
      lty.grid = lty.grid
    )
    arrows(0.12, 0.41, 0.22, 0.57, length = 0.15)
    arrows(0.78, 0.57, 0.88, 0.41, length = 0.15)
    arrows(0.6,-0.1, 0.38,-0.1, length = 0.15)
    if (show.lines) {
      triax.segments <- function(h1, h3, t1, t3, col) {
        segments(1 - h1 - h3 / 2, h3 * sin(pi / 3), 1 - t1 -
                   t3 / 2, t3 * sin(pi / 3), col = col)
      }
      h1 <- c(85, 70, 80, 52, 52, 50, 20, 8, 52, 45, 45, 65,
              45, 20, 20) / 100
      h3 <- c(0, 0, 20, 20, 7, 0, 0, 12, 20, 27, 27, 35, 40,
              27, 40) / 100
      t1 <- c(90, 85, 52, 52, 43, 23, 8, 0, 45, 0, 45, 45,
              0, 20, 0) / 100
      t3 <- c(10, 15, 20, 7, 7, 27, 12, 12, 27, 27, 55, 35,
              40, 40, 60) / 100
      triax.segments(h1, h3, t1, t3, col.lines)
    }
    if (show.names) {
      xpos <- c(
        0.5,
        0.7,
        0.7,
        0.73,
        0.73,
        0.5,
        0.275,
        0.275,
        0.27,
        0.27,
        0.25,
        0.135,
        0.18,
        0.055,
        0.49,
        0.72,
        0.9
      )
      ypos <- c(
        0.66,
        0.49,
        0.44,
        0.36,
        0.32,
        0.35,
        0.43,
        0.39,
        0.3,
        0.26,
        0.13,
        0.072,
        0.032,
        0.024,
        0.18,
        0.15,
        0.06
      ) * sin(pi / 3)
      snames <- c(
        "clay",
        "silty",
        "clay",
        "silty clay",
        "loam",
        "clay loam",
        "sandy",
        "clay",
        "sandy clay",
        "loam",
        "sandy loam",
        "loamy",
        "sand",
        "sand",
        "loam",
        "silt loam",
        "silt"
      )
      text(xpos, ypos, labels = snames)
    }
    par(xpd = FALSE)
    soilpoints <-
      plotrix::triax.points(
        texture,
        show.legend = show.legend,
        label.points = label.points,
        point.labels = point.labels,
        col.symbols = col.symbols,
        pch = pch,
        ...
      )
    if(save_plot){
      dev.off()
    }

  }

#plot_soil_3DFEM(soil_file_path,outdir = outdir,save_plot = T,pch=21,bg.symbols="red",cex=3)
